version: '2'

services:
  database:
    build: ./mysql
    volumes:
      - ../storage/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: devsummit
      MYSQL_USER: root 
      MYSQL_PASSWORD: BOZ3rWGSVxTolxabyoax
      MYSQL_ROOT_PASSWORD: BOZ3rWGSVxTolxabyoax

  web:
    depends_on:
      - database
    build: .
    container_name: devsummit
    ports:
      - "5000:5000"
    volumes:
      - .:/backend
